### ISSUE TITLE
get_drafts HTTP error 404

### ISSUE THREAD

**Issue by gregalytics** [eoppe1022/elite#1]
getting the following when I run some of the sample code. Tried with "nhl" and "nhl_entry_draft". 
> draft <- get_drafts("nhl", "2018")
get_drafts() [--------------------------------------------------------------------------------------------------]   0% eta:  ?sError in open.connection(x, "rb") : HTTP error 404.

**Comment by eoppe1022** [comment]
Hey thanks for trying the package, and apologies for the delay in my response

Have you tried `get_drafts("nhl entry draft", "2018")`? That works for me

**Comment by gregalytics** [comment]
That worked, but getting an issue on a cbind for certain draft years:
get_drafts("nhl entry draft", 2002)

**Comment by eoppe1022** [comment]
weird, I'm not sure why that's not working. I'll check that out soon

**Comment by eoppe1022** [comment]
FIXED

try re-downloading

it was a joining issue that was pretty dumb of me, but that fixed it.
